name: Windows build
permissions:
  contents: read

on:
  push:
    branches: [ OpenGL ]
  pull_request:
    branches: [ OpenGL ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         submodules: 'true'
      - name: Cmake
        run: 
         cmake -E make_directory build;
         cmake -E chdir build cmake ..
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build Solution
        run: |
         ls
         MSBuild.exe .\build\Campfire.sln
